### ISSUE TITLE
Unable to read font

### ISSUE THREAD

**Issue by hilmanski** [rizafahmi/microblog_ig#1]
I tried the sample script

sh microblog.sh \
--text="Produktif bukan berarti berbuat lebih, melainkan mengerjakan yang PENTING." \
--author="@rizafahmi" \
--background="#f9f8fc" \
--font=fonts/AmaticSC-Bold.ttf \
--filename="ig.png"

Result
convert: unable to read font `fonts/AmaticSC-Bold.ttf' @ warning/annotate.c/RenderType/971.

*image still successfully created 

Suggestion: Add an information, how to use custom font like the one in example

**Comment by rizafahmi** [comment]
Thanks @hilmanski
